version: '3.9'

services:
  cassandra_db_node_1_seed:
    container_name: cassandra_db_node_1_seed
    image: cassandra:4.1.0
#    ports:
#      - "9042:9042"
    environment:
      - "CASSANDRA_SEEDS=cassandra_db_node_1_seed"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
      #      needed for setting up custom cluster name
      - "CASSANDRA_DC=se1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    networks:
      cassandra_network:
#        ipv4_address: 172.16.238.10

  cassandra_db_node_2:
    container_name: cassandra_db_node_2
    image: cassandra:4.1.0
#    ports:
#      - "9043:9042"
    environment:
      - "CASSANDRA_SEEDS=cassandra_db_node_1_seed"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
      #      needed for setting up custom cluster name
      - "CASSANDRA_DC=se1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
#    expose:
#      - 7000
#      - 7001
#      - 7199
#      - 9042
#      - 9142
    #    volumes:
#      - ./config/node_2/cassandra_node_2.yaml:/etc/cassandra/cassandra.yaml
    networks:
      cassandra_network:
#        ipv4_address: 172.16.238.11

#  cassandra_db_node_3:
#    container_name: cassandra_db_node_3
#    image: cassandra:4.1.0
#    ports:
#      - "9044:9042"
#    environment:
#      - HEAP_NEWSIZE=128M
#      - MAX_HEAP_SIZE=2048M
#    volumes:
#      - ./config/node_3/cassandra_node_3.yaml:/etc/cassandra/cassandra.yaml
##    deploy:
##      resources:
##        limits:
##          cpus: '1'
##          memory: 3G
##        reservations:
##          cpus: '1'
##          memory: 3G
#    networks:
#      cassandra_network:
#        ipv4_address: 172.16.238.12

#  cassandra_temp:
#    image: cassandra:4.1.0
##    volumes:
##      - ./scripts/bash:/docker-entrypoint.sh
##      - ./scripts/cql:/tmp/cql
#    networks:
#      - cassandra_network
##    command: >
##      bash ./docker-entrypoint.sh/execute-cql.sh

networks:
  cassandra_network:
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.16.238.0/24